"""initial mvp schema

Revision ID: 0a47cc7879de
Revises: 
Create Date: 2026-05-15 10:32:53.546882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a47cc7879de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_minifigs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minifig_num', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('minifig_num')
    )
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('rgb', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_num', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_num')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('catalog_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_num', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('num_parts', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_num')
    )
    op.create_table('minifig_part_inventory_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_minifig_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_spare', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_minifig_part_inventory_lines_quantity'),
    sa.ForeignKeyConstraint(['catalog_minifig_id'], ['catalog_minifigs.id'], ),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_minifig_id', 'part_id', 'color_id', 'is_spare', name='uq_minifig_part_inventory_lines_natural_key')
    )
    op.create_index('ix_minifig_part_inventory_lines_catalog_minifig_id', 'minifig_part_inventory_lines', ['catalog_minifig_id'], unique=False)
    op.create_table('part_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', 'source', name='uq_part_aliases_alias_source')
    )
    op.create_index('ix_part_aliases_alias', 'part_aliases', ['alias'], unique=False)
    op.create_table('owned_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_set_id', sa.Integer(), nullable=False),
    sa.Column('investigated', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_set_id'], ['catalog_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_owned_sets_catalog_set_id', 'owned_sets', ['catalog_set_id'], unique=False)
    op.create_index('ix_owned_sets_investigated', 'owned_sets', ['investigated'], unique=False)
    op.create_table('set_minifig_inventory_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_set_id', sa.Integer(), nullable=False),
    sa.Column('catalog_minifig_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_set_minifig_inventory_lines_quantity'),
    sa.ForeignKeyConstraint(['catalog_minifig_id'], ['catalog_minifigs.id'], ),
    sa.ForeignKeyConstraint(['catalog_set_id'], ['catalog_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_set_id', 'catalog_minifig_id', name='uq_set_minifig_inventory_lines_natural_key')
    )
    op.create_index('ix_set_minifig_inventory_lines_catalog_set_id', 'set_minifig_inventory_lines', ['catalog_set_id'], unique=False)
    op.create_table('set_part_inventory_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_set_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_spare', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_alternate', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_set_part_inventory_lines_quantity'),
    sa.ForeignKeyConstraint(['catalog_set_id'], ['catalog_sets.id'], ),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_set_id', 'part_id', 'color_id', 'is_spare', 'is_alternate', name='uq_set_part_inventory_lines_natural_key')
    )
    op.create_index('ix_set_part_inventory_lines_catalog_set_id', 'set_part_inventory_lines', ['catalog_set_id'], unique=False)
    op.create_table('missing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owned_set_id', sa.Integer(), nullable=False),
    sa.Column('set_part_inventory_line_id', sa.Integer(), nullable=True),
    sa.Column('minifig_part_inventory_line_id', sa.Integer(), nullable=True),
    sa.Column('quantity_missing', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(set_part_inventory_line_id IS NOT NULL AND minifig_part_inventory_line_id IS NULL) OR (set_part_inventory_line_id IS NULL AND minifig_part_inventory_line_id IS NOT NULL)', name='ck_missing_items_one_line_ref'),
    sa.CheckConstraint('quantity_missing > 0', name='ck_missing_items_quantity_missing'),
    sa.ForeignKeyConstraint(['minifig_part_inventory_line_id'], ['minifig_part_inventory_lines.id'], ),
    sa.ForeignKeyConstraint(['owned_set_id'], ['owned_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_part_inventory_line_id'], ['set_part_inventory_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_missing_items_owned_minifig_part_line', 'missing_items', ['owned_set_id', 'minifig_part_inventory_line_id'], unique=True, sqlite_where=sa.text('minifig_part_inventory_line_id IS NOT NULL'))
    op.create_index('uq_missing_items_owned_set_part_line', 'missing_items', ['owned_set_id', 'set_part_inventory_line_id'], unique=True, sqlite_where=sa.text('set_part_inventory_line_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_missing_items_owned_set_part_line', table_name='missing_items', sqlite_where=sa.text('set_part_inventory_line_id IS NOT NULL'))
    op.drop_index('uq_missing_items_owned_minifig_part_line', table_name='missing_items', sqlite_where=sa.text('minifig_part_inventory_line_id IS NOT NULL'))
    op.drop_table('missing_items')
    op.drop_index('ix_set_part_inventory_lines_catalog_set_id', table_name='set_part_inventory_lines')
    op.drop_table('set_part_inventory_lines')
    op.drop_index('ix_set_minifig_inventory_lines_catalog_set_id', table_name='set_minifig_inventory_lines')
    op.drop_table('set_minifig_inventory_lines')
    op.drop_index('ix_owned_sets_investigated', table_name='owned_sets')
    op.drop_index('ix_owned_sets_catalog_set_id', table_name='owned_sets')
    op.drop_table('owned_sets')
    op.drop_index('ix_part_aliases_alias', table_name='part_aliases')
    op.drop_table('part_aliases')
    op.drop_index('ix_minifig_part_inventory_lines_catalog_minifig_id', table_name='minifig_part_inventory_lines')
    op.drop_table('minifig_part_inventory_lines')
    op.drop_table('catalog_sets')
    op.drop_table('themes')
    op.drop_table('parts')
    op.drop_table('colors')
    op.drop_table('catalog_minifigs')
    # ### end Alembic commands ###
